### ISSUE TITLE
Setup tips

### ISSUE THREAD

**Issue by 1tylermitchell** [tcolgate/tsdb-dash#2]
Looking forward to putting this through its paces as I was working on something similar.  I'm new to the tree concept used here.  Is there some metric setup that has to be done before using the trees as you describe in the readme?
i.e. I get this kind of response in error logs...

`Bad Request on /api/tree/branch?branch=0001: Unable to locate branch '0001' for tree '1'`

**Comment by tcolgate** [comment]
Hi. I'm really sorry I missed these posts. If you are still interested I can give you some help. The code is very buggy at the moment and not particularly functional. But if you are looking to help out, or can put up with broken stuff, it'd be great.

**Comment by tcolgate** [comment]
I've added a few more setup tips, and coments about the tree setup
